### ISSUE TITLE
Any way to not rely on Spring ?

### ISSUE THREAD

**Issue by cescoffier** [apacheignite/vertx-ignite#1]
Is there a way to not rely on Spring for the configuration ? It just brings a lot of dependencies that are not really relevant (smaller the better to avoid conflict in fat jars).

**Comment by agura** [comment]
Unfortunately spring configuration is only way to configure Ignite except programmatically configuration.

**Comment by dsetrakyan** [comment]
All we are using from Spring, is a basic Pojo configuration. No other features are used. Spring actually has been very good with maintaining backward compatibility, and has not caused any versioning issues for Ignite users.

Having said that, Andrey, is there an option to programmatically configure Ignite with Vert.x?

**Comment by cescoffier** [comment]
I saw quite some dependencies downloaded. Maybe we can have a look to exclude some ?

The main issue is when users are going to package it as a fat jar, and use / expect a newer version. Depending on the packaging process it may not take the right version.

Right now, it requires the following dependencies:

```
[INFO] +- org.apache.ignite:ignite-spring:jar:1.5.0.final:compile
[INFO] |  +- org.springframework:spring-core:jar:4.1.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.1.0.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- org.springframework:spring-beans:jar:4.1.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-context:jar:4.1.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-expression:jar:4.1.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-tx:jar:4.1.0.RELEASE:compile
[INFO] |  +- org.springframework:spring-jdbc:jar:4.1.0.RELEASE:compile
[INFO] |  \- commons-logging:commons-logging:jar:1.1.1:compile
```

I'm not sure that tx, jdbc are required. For the other dependencies, I don't know.

**Comment by agura** [comment]
Clement,

we can explicitly exclude the following dependencies (and their dependencies of course):
- `org.springframework:spring-aop`
- `org.springframework:spring-tx`
- `org.springframework:spring-jdbc`

Is it ok?

**Comment by cescoffier** [comment]
Yes definitely, thanks !
