### ISSUE TITLE
Ignite Cache access blocks the event loop

### ISSUE THREAD

**Issue by cescoffier** [apacheignite/vertx-ignite#4]
For example, `io.vertx.spi.cluster.ignite.impl.AsyncMultiMapImpl#get` is blocking.

The access to the cache (`cache.get(key)`) is executed in the event loop and may block the event loop.
`IgniteCache.get` usage needs to be refactored to not block the event loop.

**Comment by agura** [comment]
Clement,

why do you think that cache access methods are blocking? Did you see any messages from event loop blocking checker thread or something other? If no, I'll try to clarify `AsyncMultiMapImpl` implementation below.

All cache access methods of `io.vertx.spi.cluster.ignite.impl.AsyncMultiMapImpl` are non-blocking. See `execute` method. It performs async operation on cache, doesn't wait for result, gets future associated with performed operation and register listener on that future. When operation will completed it completes future also and listener will be invoked. This listener will invoke vert.x handler with async result obtained from Ignite future.

**Comment by cescoffier** [comment]
If we consider the `execute` method from `AsyncMultiMapImpl`, there is a `cacheOp.accept(cache)` call. This call is, if I'm not mistaken, executed in the event loop thread. 

The `get` method implementation is the following:

```
execute(
        cache -> cache.get(key),
        (List<V> list) -> new ChoosableIterableImpl<>(list == null ? Collections.<V>emptyList() : list),
        handler
    );
```

So the `cache.get(key)`, the `cacheOp`, is executed in the event loop, and this call is blocking.

**Comment by agura** [comment]
But `cache.get(key)` call is async because is called on async cache facade (`this.cache.withAsync()`). `get(key)` method returns immediately in case of async facade.

This blog post can clarify async facade: http://gridgain.blogspot.ru/2015/03/asynchronous-apis-done-right.html

**Comment by cescoffier** [comment]
Oh I see, sorry, I'm a Ignite beginner (never used it before).

The blog post is really good, thanks !
